# Generated by Django 5.1.6 on 2025-03-11 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_desc',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_name',
        ),
        migrations.CreateModel(
            name='Has',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.skill')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.user')),
            ],
        ),
        migrations.CreateModel(
            name='Requires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.job')),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.skill')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skill_name',
            field=models.ManyToManyField(to='jobsearch.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_name',
            field=models.ManyToManyField(to='jobsearch.skill'),
        ),
    ]
