# Generated by Django 5.1.6 on 2025-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0003_city_county_state_remove_requires_job_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altskill',
            old_name='skill_name',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='skill_name',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='site',
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_name',
            field=models.ManyToManyField(blank=True, to='jobsearch.skill'),
        ),
    ]
