# Generated by Django 5.1.6 on 2025-03-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0004_rename_skill_name_altskill_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altskill',
            old_name='skill',
            new_name='skill_name',
        ),
    ]
