# Generated by Django 5.1.6 on 2025-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0006_rename_skill_name_altskill_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
