# Generated by Django 5.1.6 on 2025-03-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0008_alter_skill_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsearch.city'),
        ),
    ]
