# Generated by Django 5.1.6 on 2025-03-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0009_job_education_alter_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=600),
        ),
    ]
