# Generated by Django 5.1.6 on 2025-03-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0010_alter_job_company_alter_job_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altskill',
            name='alt_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
