# Generated by Django 5.1.7 on 2025-04-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0013_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='fips',
            field=models.CharField(default='', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
